name: Scala CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Run tests
      run: sbt '; set parallelExecution in Test := false; testQuick -- -l com.ing.util.CassandraTag'
    - name: Run tests generated IT
      run: sbt '; set parallelExecution in Test := false; generated/it:testQuick -- -l com.ing.util.CassandraTag'
    - name: Run tests generated multi jvm
      run: sbt '; set parallelExecution in Test := false; generated/multi-jvm:testQuick -- -l com.ing.util.CassandraTag'
